version: "3"

services:
  django:
    container_name: root_source
    build: django.Dockerfile
    volumes:
      - .:/alphagolite

    stdin_open: true
    tty: true
    ports:
      - 8000:8000

  redis:
    container_name: sockets
    image: redis:5
    ports:
      - 6379:6379

  frontend:
    container_name: react_js
    build: frontend.Dockerfile
    volumes:
      - .:/alphagolite

    stdin_open: true
    tty: true

    depends_on:
      - django
