version: "3"

services:
  django_and_main:
    container_name: django_and_main
    build:
      context: .
      dockerfile: django.Dockerfile
    volumes:
      - .:/alphagolite

    stdin_open: true
    tty: true
    ports:
      - 8000:8000

  redis:
    container_name: sockets
    image: redis:5
    ports:
      - 6379:6379

  frontend:
    container_name: react_js
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - ./play_go_web_app/frontend:/frontend

    stdin_open: true
    tty: true

    depends_on:
      - django_and_main
