# Generated by Django 3.1.6 on 2022-01-03 17:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('player1', models.CharField(default=api.models.randomNameP1, max_length=50)),
                ('player2', models.CharField(default=api.models.randomNameP2, max_length=50)),
                ('player1_color', models.CharField(default=api.models.pickRandomColor, max_length=7)),
                ('player2_color', models.CharField(default=api.models.pickRandomColor, max_length=7)),
                ('num_spectators', models.IntegerField(default=0)),
                ('curr_turn', models.BooleanField(default=True)),
                ('player1_turn', models.BooleanField(default=True)),
                ('player2_turn', models.BooleanField(default=False)),
                ('AI', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=765)),
                ('spectator_list', models.CharField(default='[]', max_length=275)),
            ],
        ),
    ]
