# Generated by Django 3.1.6 on 2022-01-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host1',
            field=models.CharField(default='NONE', max_length=50, unique=True),
        ),
    ]
