# Generated by Django 3.2.3 on 2021-05-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_room_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='board',
            field=models.CharField(default='[]', max_length=765),
        ),
    ]
