# Generated by Django 3.2.3 on 2021-05-22 04:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='player1',
            field=models.CharField(default=api.models.randomNameP1, max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='player2',
            field=models.CharField(default=api.models.randomNameP2, max_length=50),
        ),
    ]
