# Generated by Django 3.1.6 on 2021-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='AI',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
